# Generated by Django 6.0.1 on 2026-02-17 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIYProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('step_count', models.IntegerField()),
                ('estimated_time', models.DurationField()),
                ('is_rental_safe', models.BooleanField(default=True)),
                ('requires_drilling', models.BooleanField(default=False)),
                ('materials_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction_text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pages.diyproject')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
