# Generated by Django 6.0.1 on 2026-02-28 19:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, choices=[('GE', 'GE'), ('LG', 'LG'), ('Whirlpool', 'Whirlpool'), ('Frigidaire', 'Frigidaire'), ('Samsung', 'Samsung'), ('Bosch', 'Bosch'), ('KitchenAid', 'KitchenAid'), ('Maytag', 'Maytag'), ('Kenmore', 'Kenmore'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=64)),
                ('model_number', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('General', 'General'), ('Appliance', 'Appliance'), ('Furniture', 'Furniture')], default='general', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('consumable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='pages.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=64)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('retail_url', models.URLField(blank=True)),
                ('consumable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages.consumable')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_consumable_details', to='pages.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='HomeUserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_user_connections', to='pages.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_user_connections', to='pages.appuser')),
            ],
            options={
                'unique_together': {('home', 'user')},
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='homes',
            field=models.ManyToManyField(blank=True, related_name='users', through='pages.HomeUserConnection', to='pages.home'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pages.home')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pages.room'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('interval', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=16)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.asset')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.consumable')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.home')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.room')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pages.task')),
            ],
        ),
    ]
