# Generated by Django 6.0.1 on 2026-02-21 18:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='j@j.com', max_length=254),
            preserve_default=False,
        ),
    ]
