# Generated by Django 6.0.1 on 2026-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyproject',
            name='tools_json',
            field=models.JSONField(default=list),
        ),
    ]
