# Generated by Django 6.0.1 on 2026-02-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
