# Generated by Django 6.0.1 on 2026-02-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_task_last_completed_date_task_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=16),
        ),
    ]
