# Generated by Django 6.0.1 on 2026-02-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_task_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('appliance', 'Appliance'), ('furniture', 'Furniture')], default='general', max_length=32),
        ),
    ]
