# Generated by Django 6.0.1 on 2026-02-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_asset_model_number_alter_asset_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='retail_url',
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('model_number', models.CharField(blank=True, max_length=64)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_asset_details', to='pages.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pages.assetdetails'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='pages.assetdetails'),
        ),
        migrations.CreateModel(
            name='ConsumableDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=64)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('retail_url', models.URLField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_consumable_details', to='pages.appuser')),
            ],
        ),
    ]
