# Generated by Django 6.0.1 on 2026-02-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_asset_brand_remove_asset_model_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='pages.consumabledetails'),
        ),
    ]
